### ISSUE TITLE
Diagrama ausente

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-castv#3]
Ya no está disponible el diagrama de flujo.

**Comment by alejandro-valderrabano-sanchez** [comment]
Ya lo hemos corregido, habrá sido un descuido.

**Comment by alejandro-valderrabano-sanchez** [comment]
Ya se ha corregido, habrá sido un descuido.

**Comment by oscarperpinan** [comment]
Ok. No olvidéis cerrar esta issue.
